name: delete files

on:
  schedule:
    - cron: "0 22 * * *"

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: echo "python机器人开始工作"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install json
        pip install requests
        pip install datetime
    - name: do work
      env:
        MW_USERNAME: ${{secrets.SBOT_NAME}} 
        MW_PASSWORD: ${{secrets.SBOT_PASSWORD}}
      run: |
        src/sync_deleteflie.py
